#!/bin/bash
#
# Mikan Helm chart installer (standalone).
# If .env does not exist, interactively creates one.
# Then generates a helm install command.
#
# Usage: ./install.sh [path-to-env-file]
#
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${1:-$SCRIPT_DIR/.env}"

# --- Create .env if it doesn't exist ---
if [ ! -f "$ENV_FILE" ]; then
  echo ""
  echo "=== Mikan Helm Chart - Initial Setup ==="
  echo ""
  echo "No .env file found. Let's create one."
  echo ""

  # Database
  echo "-- Database (external) --"
  read -rp "Database host (e.g., my-rds.xxx.rds.amazonaws.com): " DATABASE_HOST
  read -rp "Database port (default: 5432): " DATABASE_PORT
  DATABASE_PORT="${DATABASE_PORT:-5432}"
  read -rp "Database username (default: postgres): " DATABASE_USERNAME
  DATABASE_USERNAME="${DATABASE_USERNAME:-postgres}"
  read -rsp "Database password: " DATABASE_PASSWORD
  echo ""
  read -rp "Database name (default: mikan): " DATABASE_NAME
  DATABASE_NAME="${DATABASE_NAME:-mikan}"
  read -rp "Enable SSL? [true/false] (default: true): " DATABASE_SSL
  DATABASE_SSL="${DATABASE_SSL:-true}"
  echo ""

  # Confluent
  echo "-- Confluent Cloud API credentials --"
  read -rp "Confluent API key: " CONFLUENT_API_KEY
  read -rsp "Confluent API secret: " CONFLUENT_API_SECRET
  echo ""
  echo ""

  # Encryption key
  echo "-- Encryption key --"
  ENCRYPTION_KEY=$(openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c 64 2>/dev/null || true)
  if [ -n "$ENCRYPTION_KEY" ]; then
    echo "Auto-generated encryption key."
  else
    read -rp "Encryption key (64 chars): " ENCRYPTION_KEY
  fi
  echo ""

  # Write .env
  cat > "$ENV_FILE" <<EOF
# Mikan Helm Chart - Environment Configuration
# Generated by install.sh

# -- Helm release settings
# CHART_REF=oci://public.ecr.aws/q0l2x1j9/mikan-chart-staging
RELEASE_NAME=mikan

# -- Image settings
IMAGE_TAG=latest

# -- Database (external)
DATABASE_HOST=$DATABASE_HOST
DATABASE_PORT=$DATABASE_PORT
DATABASE_USERNAME=$DATABASE_USERNAME
DATABASE_PASSWORD=$DATABASE_PASSWORD
DATABASE_NAME=$DATABASE_NAME
DATABASE_SSL=$DATABASE_SSL

# -- Confluent Cloud API credentials
CONFLUENT_API_KEY=$CONFLUENT_API_KEY
CONFLUENT_API_SECRET=$CONFLUENT_API_SECRET

# -- Encryption key
ENCRYPTION_KEY=$ENCRYPTION_KEY

# -- App settings
CORS_ALLOWED_ORIGINS=*
VITE_API_URL=http://localhost:3333/graphql

# -- Ingress (optional, coming soon)
# INGRESS_HOST=
# ACM_CERTIFICATE_ARN=

# -- Azure AD (optional)
# AZURE_CLIENT_ID=
# AZURE_CLIENT_SECRET=
# AZURE_TENANT_ID=
EOF

  echo "Created $ENV_FILE"
  echo ""
fi

# --- Load .env ---
set -a
source "$ENV_FILE"
set +a

# Support both variable naming conventions
CONFLUENT_API_KEY="${CONFLUENT_API_KEY:-$CONFLUENT_MANAGEMENT_API_KEY}"
CONFLUENT_API_SECRET="${CONFLUENT_API_SECRET:-$CONFLUENT_MANAGEMENT_API_SECRET}"

# --- Chart source ---
CHART_REF="${CHART_REF:-oci://public.ecr.aws/q0l2x1j9/mikan-chart-staging}"
RELEASE_NAME="${RELEASE_NAME:-mikan}"

# --- Interactive: Namespace ---
echo ""
echo "=== Mikan Helm Chart Installer ==="
echo ""
read -rp "Kubernetes namespace (default: mikan): " NAMESPACE
NAMESPACE="${NAMESPACE:-mikan}"

# --- Interactive: Ingress ---
echo ""
echo "How do you want to expose Mikan?"
echo ""
echo "  1) ALB Ingress (coming soon)"
echo ""
echo "  2) No Ingress (use kubectl port-forward)"
echo "     - No additional setup required"
echo "     - Access via: kubectl port-forward svc/$RELEASE_NAME-app 3000:3000 -n $NAMESPACE"
echo ""
read -rp "Select [1/2] (default: 2): " INGRESS_CHOICE
INGRESS_CHOICE="${INGRESS_CHOICE:-2}"

if [ "$INGRESS_CHOICE" = "1" ]; then
  echo ""
  echo "ALB Ingress support is coming soon. Please use option 2 (port-forward) for now."
  echo ""
  exit 0
fi

# --- Build helm command ---
ARGS=()
ARGS+=("-n $NAMESPACE --create-namespace")
ARGS+=("--set fullnameOverride=\"$RELEASE_NAME\"")
ARGS+=("--set global.imageTag=\"$IMAGE_TAG\"")
ARGS+=("--set database.external=true")
ARGS+=("--set database.host=\"$DATABASE_HOST\"")
ARGS+=("--set database.port=\"$DATABASE_PORT\"")
ARGS+=("--set database.username=\"$DATABASE_USERNAME\"")
ARGS+=("--set database.password=\"$DATABASE_PASSWORD\"")
ARGS+=("--set database.name=\"$DATABASE_NAME\"")
ARGS+=("--set database.ssl=\"$DATABASE_SSL\"")
ARGS+=("--set api.confluent.apiKey=\"$CONFLUENT_API_KEY\"")
ARGS+=("--set api.confluent.apiSecret=\"$CONFLUENT_API_SECRET\"")
ARGS+=("--set api.encryptionKey=\"$ENCRYPTION_KEY\"")
ARGS+=("--set api.env.CORS_ALLOWED_ORIGINS=\"$CORS_ALLOWED_ORIGINS\"")
ARGS+=("--set app.env.VITE_API_URL=\"$VITE_API_URL\"")

if [ -n "$AZURE_CLIENT_ID" ]; then
  ARGS+=("--set api.azure.clientId=\"$AZURE_CLIENT_ID\"")
  ARGS+=("--set api.azure.clientSecret=\"$AZURE_CLIENT_SECRET\"")
  ARGS+=("--set api.azure.tenantId=\"$AZURE_TENANT_ID\"")
fi

# --- Print command ---
echo ""
echo "# Generated helm command from: $ENV_FILE"
echo "# Review and run:"
echo ""
echo -n "helm upgrade --install $RELEASE_NAME $CHART_REF"
for arg in "${ARGS[@]}"; do
  echo " \\"
  echo -n "  $arg"
done
echo ""
echo ""

# --- Post-install guidance ---
echo "# --- Access via port-forward ---"
echo "# kubectl port-forward svc/$RELEASE_NAME-app 3000:3000 -n $NAMESPACE &"
echo "# kubectl port-forward svc/$RELEASE_NAME-api 3333:3333 -n $NAMESPACE &"
echo "#"
echo "# Then open http://localhost:3000"
echo ""

echo "# --- Default login credentials ---"
echo "# Email:    admin@mikan.local"
echo "# Password: SuperAdmin123!"
echo "#"
echo "# Please change the password after first login."
echo ""
