#!/bin/bash
#
# Mikan Helm chart installer (standalone).
# If .env does not exist, interactively creates one.
# Then generates a helm install command.
#
# Usage: ./install.sh [path-to-env-file]
#
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${1:-$SCRIPT_DIR/.env}"

ECR_REGISTRY="624622221797.dkr.ecr.us-east-1.amazonaws.com"

# --- ECR Login with token ---
ecr_login() {
  echo ""
  echo "=== ECR Login ==="
  echo ""
  echo "  Enter the ECR Token provided by the Mikan team."
  echo "  (Contact mikan@goodlabs.studio if you don't have a token)"
  echo ""

  while true; do
    while [ -z "$ECR_TOKEN" ]; do
      if command -v stty &> /dev/null; then
        stty -icanon 2>/dev/null || true
      fi
      echo -n "  Enter ECR Token: "
      ECR_TOKEN=$(head -n 1)
      if command -v stty &> /dev/null; then
        stty icanon 2>/dev/null || true
      fi
      ECR_TOKEN=$(echo "$ECR_TOKEN" | tr -d '\n\r ')
      if [ -z "$ECR_TOKEN" ]; then
        echo "  [ERROR] ECR Token is required."
      fi
    done

    echo ""
    echo "Logging in to Helm OCI registry..."
    if echo "$ECR_TOKEN" | helm registry login --username AWS --password-stdin "$ECR_REGISTRY" 2>/dev/null; then
      echo "  [OK] Helm registry login successful"
      break
    else
      echo "  [ERROR] Helm registry login failed. Please check your ECR token."
      echo ""
      read -rp "Do you want to re-enter the ECR token? (y/N): " retry
      if [[ ! "$retry" =~ ^[Yy]$ ]]; then
        echo "Installation cancelled."
        exit 1
      fi
      ECR_TOKEN=""
    fi
  done
  echo ""
}

ecr_login

# --- Create .env if it doesn't exist ---
if [ ! -f "$ENV_FILE" ]; then
  echo ""
  echo "=== Mikan Helm Chart - Initial Setup ==="
  echo ""
  echo "No .env file found. Let's create one."
  echo ""

  # Database
  echo "-- Database (external) --"
  read -rp "Database host (e.g., my-rds.xxx.rds.amazonaws.com): " DATABASE_HOST
  read -rp "Database port (default: 5432): " DATABASE_PORT
  DATABASE_PORT="${DATABASE_PORT:-5432}"
  read -rp "Database username (default: postgres): " DATABASE_USERNAME
  DATABASE_USERNAME="${DATABASE_USERNAME:-postgres}"
  read -rsp "Database password: " DATABASE_PASSWORD
  echo ""
  read -rp "Database name (default: mikan): " DATABASE_NAME
  DATABASE_NAME="${DATABASE_NAME:-mikan}"
  read -rp "Enable SSL? [true/false] (default: true): " DATABASE_SSL
  DATABASE_SSL="${DATABASE_SSL:-true}"
  echo ""

  # Confluent
  echo "-- Confluent Cloud API credentials --"
  read -rp "Confluent API key: " CONFLUENT_API_KEY
  read -rsp "Confluent API secret: " CONFLUENT_API_SECRET
  echo ""
  echo ""

  # Encryption key
  echo "-- Encryption key --"
  read -rp "Encryption key (leave empty to auto-generate): " ENCRYPTION_KEY
  if [ -z "$ENCRYPTION_KEY" ]; then
    ENCRYPTION_KEY=$(openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c 64 2>/dev/null || true)
    if [ -n "$ENCRYPTION_KEY" ]; then
      echo "Auto-generated encryption key."
    else
      read -rp "Auto-generation failed. Enter encryption key (64 chars): " ENCRYPTION_KEY
    fi
  fi
  echo ""

  # Ingress
  echo "-- Ingress --"
  read -rp "Enable ingress? [true/false] (default: true): " INGRESS_ENABLED
  INGRESS_ENABLED="${INGRESS_ENABLED:-true}"
  if [ "$INGRESS_ENABLED" = "true" ]; then
    read -rp "Ingress scheme [internet-facing/internal] (default: internet-facing): " INGRESS_SCHEME
    INGRESS_SCHEME="${INGRESS_SCHEME:-internet-facing}"
    read -rp "Ingress host (e.g., mikan.example.com, leave empty to skip): " INGRESS_HOST
    read -rp "ACM certificate ARN (leave empty to skip): " ACM_CERTIFICATE_ARN
  else
    INGRESS_SCHEME="internet-facing"
    INGRESS_HOST=""
    ACM_CERTIFICATE_ARN=""
  fi
  echo ""

  # Determine VITE_API_URL based on ingress
  if [ "$INGRESS_ENABLED" = "true" ]; then
    VITE_API_URL="/graphql"
  else
    VITE_API_URL="http://localhost:3333/graphql"
  fi

  # Write .env
  cat > "$ENV_FILE" <<EOF
# Mikan Helm Chart - Environment Configuration
# Generated by install.sh

# -- Helm release settings
# CHART_REF=oci://624622221797.dkr.ecr.us-east-1.amazonaws.com/mikan-chart-staging/mikan
RELEASE_NAME=mikan

# -- Image settings
IMAGE_TAG=latest

# -- Database (external)
DATABASE_HOST=$DATABASE_HOST
DATABASE_PORT=$DATABASE_PORT
DATABASE_USERNAME='$DATABASE_USERNAME'
DATABASE_PASSWORD='$DATABASE_PASSWORD'
DATABASE_NAME=$DATABASE_NAME
DATABASE_SSL=$DATABASE_SSL

# -- Confluent Cloud API credentials
CONFLUENT_API_KEY='$CONFLUENT_API_KEY'
CONFLUENT_API_SECRET='$CONFLUENT_API_SECRET'

# -- Encryption key
ENCRYPTION_KEY='$ENCRYPTION_KEY'

# -- App settings
CORS_ALLOWED_ORIGINS=*
VITE_API_URL=$VITE_API_URL

# -- Ingress
INGRESS_ENABLED=$INGRESS_ENABLED
INGRESS_SCHEME=$INGRESS_SCHEME
INGRESS_HOST=$INGRESS_HOST
ACM_CERTIFICATE_ARN=$ACM_CERTIFICATE_ARN

# -- Azure AD (optional)
# AZURE_CLIENT_ID=
# AZURE_CLIENT_SECRET=
# AZURE_TENANT_ID=
EOF

  echo "Created $ENV_FILE"
  echo ""
fi

# --- Load .env ---
set -a
source "$ENV_FILE"
set +a

# --- Interactive: Environment ---
echo ""
echo "Select deployment environment:"
echo ""
echo "  1) Staging"
echo "  2) Production"
echo ""
read -rp "Select [1/2] (default: 1): " ENV_CHOICE
ENV_CHOICE="${ENV_CHOICE:-1}"

if [ "$ENV_CHOICE" = "2" ]; then
  DEPLOY_ENV="production"
  VALUES_FILE="$SCRIPT_DIR/mikan/values-production.yaml"
else
  DEPLOY_ENV="staging"
  VALUES_FILE="$SCRIPT_DIR/mikan/values-staging.yaml"
fi

echo "Using environment: $DEPLOY_ENV"

# Support both variable naming conventions
CONFLUENT_API_KEY="${CONFLUENT_API_KEY:-$CONFLUENT_MANAGEMENT_API_KEY}"
CONFLUENT_API_SECRET="${CONFLUENT_API_SECRET:-$CONFLUENT_MANAGEMENT_API_SECRET}"

# --- Chart source ---
if [ "$DEPLOY_ENV" = "production" ]; then
  CHART_REF="${CHART_REF:-oci://624622221797.dkr.ecr.us-east-1.amazonaws.com/mikan-chart-production/mikan}"
else
  CHART_REF="${CHART_REF:-oci://624622221797.dkr.ecr.us-east-1.amazonaws.com/mikan-chart-staging/mikan}"
fi
RELEASE_NAME="${RELEASE_NAME:-mikan}"

# --- Interactive: Namespace ---
echo ""
echo "=== Mikan Helm Chart Installer ==="
echo ""
DEFAULT_NS="mikan-${DEPLOY_ENV}"
read -rp "Kubernetes namespace (default: $DEFAULT_NS): " NAMESPACE
NAMESPACE="${NAMESPACE:-$DEFAULT_NS}"

# --- Build helm command ---
ARGS=()
ARGS+=("-n $NAMESPACE --create-namespace")
ARGS+=("--set fullnameOverride=\"$RELEASE_NAME\"")
ARGS+=("--set global.imageTag=\"$IMAGE_TAG\"")
ARGS+=("--set database.external=true")
ARGS+=("--set database.host=\"$DATABASE_HOST\"")
ARGS+=("--set database.port=\"$DATABASE_PORT\"")
ARGS+=("--set database.username=\"$DATABASE_USERNAME\"")
ARGS+=("--set database.password=\"$DATABASE_PASSWORD\"")
ARGS+=("--set database.name=\"$DATABASE_NAME\"")
ARGS+=("--set database.ssl=\"$DATABASE_SSL\"")
ARGS+=("--set api.confluent.apiKey=\"$CONFLUENT_API_KEY\"")
ARGS+=("--set api.confluent.apiSecret=\"$CONFLUENT_API_SECRET\"")
ARGS+=("--set api.encryptionKey=\"$ENCRYPTION_KEY\"")
ARGS+=("--set api.env.CORS_ALLOWED_ORIGINS=\"$CORS_ALLOWED_ORIGINS\"")
ARGS+=("--set app.env.VITE_API_URL=\"$VITE_API_URL\"")

# Ingress
if [ "${INGRESS_ENABLED:-false}" = "true" ]; then
  ARGS+=("--set ingress.enabled=true")
  ARGS+=("--set ingress.className=alb")
  if [ -n "$INGRESS_HOST" ]; then
    ARGS+=("--set ingress.host=\"$INGRESS_HOST\"")
  fi
fi

if [ -n "$AZURE_CLIENT_ID" ]; then
  ARGS+=("--set api.azure.clientId=\"$AZURE_CLIENT_ID\"")
  ARGS+=("--set api.azure.clientSecret=\"$AZURE_CLIENT_SECRET\"")
  ARGS+=("--set api.azure.tenantId=\"$AZURE_TENANT_ID\"")
fi

# --- Print command ---
echo ""
echo "# Generated helm command from: $ENV_FILE"
echo "# Review and run:"
echo ""
echo -n "helm upgrade --install $RELEASE_NAME $CHART_REF -f $VALUES_FILE"
for arg in "${ARGS[@]}"; do
  echo " \\"
  echo -n "  $arg"
done
echo ""
echo ""

# --- Post-install guidance ---
if [ "${INGRESS_ENABLED:-false}" = "true" ]; then
  echo "# --- Access via ALB Ingress ---"
  echo "# kubectl get ingress -n $NAMESPACE"
  echo "# Open the ADDRESS shown in the output"
  echo ""
else
  echo "# --- Access via port-forward ---"
  echo "# kubectl port-forward svc/$RELEASE_NAME-app 3000:3000 -n $NAMESPACE &"
  echo "# kubectl port-forward svc/$RELEASE_NAME-api 3333:3333 -n $NAMESPACE &"
  echo "#"
  echo "# Then open http://localhost:3000"
  echo ""
fi

echo "# --- Default login credentials ---"
echo "# Email:    admin@mikan.local"
echo "# Password: SuperAdmin123!"
echo "#"
echo "# Please change the password after first login."
echo ""
